name: fatsecret_nutrition
description: A Dart package for interacting with the FatSecret Nutrition API
version: 0.1.0+5
homepage: https://github.com/f3software/fatsecret_nutrition

environment:
  sdk: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ">=7.0.0 <9.0.0"

dependencies:
  dio: ^5.8.0+1
  dotenv: ^4.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  sortedmap: ^0.5.4
