name: fatsecret_nutrition
description: A Dart package for interacting with the FatSecret Nutrition API
version: 0.1.0+1
homepage: https://github.com/f3software/fatsecret_nutrition

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dependencies:
  dio: ^5.8.0+1
  dotenv: ^4.2.0
  http: ^1.4.0
  sortedmap: ^0.5.4
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.15
  json_annotation: ^4.9.0
